
package at.jku.ce.airline.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import at.jku.ce.juddi.UddiManager;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2014-11-30T13:23:25.830+01:00
 * Generated source version: 2.3.7
 * 
 */
public final class AirlineServiceImpl_AirlineServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.airline.ce.jku.at/", "AirlineServiceImplService");

    private AirlineServiceImpl_AirlineServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        UddiManager manager = UddiManager.getInstance();
        for(String wsdlURL : manager.getAllPublishedAccessPoints()){
        	AirlineServiceImplService ss = new AirlineServiceImplService(new URL(wsdlURL), SERVICE_NAME);
        	AirlineServiceImpl port = ss.getAirlineServiceImplPort();  
            
            System.out.println("[WSDL]: "+ wsdlURL);
            System.out.println("[Airline]: "+ port.getAirline().getName());
            for(Flight f : port.getAirline().getFlightPlan()){
            	System.out.println(">>====Flight begin====<<");
            	System.out.println("Flight id: "+ f.getFlightId());
            	System.out.println("Flight id: "+ f.getStdFee());
            	System.out.println(">>====Flight end====<<");
            }
        }

        System.exit(0);
    }

}
