/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package at.jku.ce.airline.service;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.3.7 2014-11-30T13:23:25.875+01:00
 * Generated source version: 2.3.7
 *
 */

@javax.jws.WebService(serviceName = "AirlineServiceImplService", portName = "AirlineServiceImplPort", targetNamespace = "http://service.airline.ce.jku.at/", wsdlLocation = "http://140.78.73.67:8080/AirlineService/services/airlineservice?wsdl", endpointInterface = "at.jku.ce.airline.service.AirlineServiceImpl")
public class AirlineServiceImplImpl implements AirlineServiceImpl {

	private static final Logger LOG = Logger
			.getLogger(AirlineServiceImplImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * at.jku.ce.airline.service.AirlineServiceImpl#getFlight(java.lang.String
	 * flightId )*
	 */
	@Override
	public at.jku.ce.airline.service.Flight getFlight(java.lang.String flightId) {
		LOG.info("Executing operation getFlight");
		System.out.println(flightId);
		try {
			at.jku.ce.airline.service.Flight _return = new at.jku.ce.airline.service.Flight();
			at.jku.ce.airline.service.Time _returnArrivalTime = new at.jku.ce.airline.service.Time();
			_returnArrivalTime.setIndexDayOfWeek(-1137364300);
			_returnArrivalTime.setTimeOfDay(359922695333172442l);
			_return.setArrivalTime(_returnArrivalTime);
			at.jku.ce.airline.service.Airport _returnArrivesAt = new at.jku.ce.airline.service.Airport();
			_returnArrivesAt.setAirportTax(new java.math.BigDecimal(
					"-7087938943143921736.7701053065514333961"));
			_returnArrivesAt.setCity("City1438211757");
			_returnArrivesAt.setCountry("Country-1106683158");
			_returnArrivesAt.setIcao("Icao-131431372");
			_returnArrivesAt.setName("Name-157441350");
			_return.setArrivesAt(_returnArrivesAt);
			at.jku.ce.airline.service.Airport _returnDepartesFrom = new at.jku.ce.airline.service.Airport();
			_returnDepartesFrom.setAirportTax(new java.math.BigDecimal(
					"3823210928058738512.731030133967692572"));
			_returnDepartesFrom.setCity("City-212226733");
			_returnDepartesFrom.setCountry("Country1419771356");
			_returnDepartesFrom.setIcao("Icao1825089524");
			_returnDepartesFrom.setName("Name461535508");
			_return.setDepartesFrom(_returnDepartesFrom);
			at.jku.ce.airline.service.Time _returnDepartureTime = new at.jku.ce.airline.service.Time();
			_returnDepartureTime.setIndexDayOfWeek(921555649);
			_returnDepartureTime.setTimeOfDay(6075145738622805102l);
			_return.setDepartureTime(_returnDepartureTime);
			_return.setFlightId("FlightId931961897");
			_return.setPlaneName("PlaneName2089277968");
			_return.setStdFee(new java.math.BigDecimal(
					"2763594680211222947.4324937472096968304"));
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see at.jku.ce.airline.service.AirlineServiceImpl#getFlightplan(*
	 */
	@Override
	public java.util.List<at.jku.ce.airline.service.Flight> getFlightplan() {
		LOG.info("Executing operation getFlightplan");
		try {
			java.util.List<at.jku.ce.airline.service.Flight> _return = new java.util.ArrayList<at.jku.ce.airline.service.Flight>();
			at.jku.ce.airline.service.Flight _returnVal1 = new at.jku.ce.airline.service.Flight();
			at.jku.ce.airline.service.Time _returnVal1ArrivalTime = new at.jku.ce.airline.service.Time();
			_returnVal1ArrivalTime.setIndexDayOfWeek(1922001879);
			_returnVal1ArrivalTime.setTimeOfDay(-3235470935772013863l);
			_returnVal1.setArrivalTime(_returnVal1ArrivalTime);
			at.jku.ce.airline.service.Airport _returnVal1ArrivesAt = new at.jku.ce.airline.service.Airport();
			_returnVal1ArrivesAt.setAirportTax(new java.math.BigDecimal(
					"3184229300642597856.2731117605422719245"));
			_returnVal1ArrivesAt.setCity("City-2107669314");
			_returnVal1ArrivesAt.setCountry("Country-1665725910");
			_returnVal1ArrivesAt.setIcao("Icao268461372");
			_returnVal1ArrivesAt.setName("Name2004535160");
			_returnVal1.setArrivesAt(_returnVal1ArrivesAt);
			at.jku.ce.airline.service.Airport _returnVal1DepartesFrom = new at.jku.ce.airline.service.Airport();
			_returnVal1DepartesFrom.setAirportTax(new java.math.BigDecimal(
					"-5060430819181532820.4568862886471818522"));
			_returnVal1DepartesFrom.setCity("City-1426526517");
			_returnVal1DepartesFrom.setCountry("Country-285683017");
			_returnVal1DepartesFrom.setIcao("Icao1741003913");
			_returnVal1DepartesFrom.setName("Name772450921");
			_returnVal1.setDepartesFrom(_returnVal1DepartesFrom);
			at.jku.ce.airline.service.Time _returnVal1DepartureTime = new at.jku.ce.airline.service.Time();
			_returnVal1DepartureTime.setIndexDayOfWeek(-468934330);
			_returnVal1DepartureTime.setTimeOfDay(6393453015423231081l);
			_returnVal1.setDepartureTime(_returnVal1DepartureTime);
			_returnVal1.setFlightId("FlightId1259440817");
			_returnVal1.setPlaneName("PlaneName1708472057");
			_returnVal1.setStdFee(new java.math.BigDecimal(
					"9028305283047332868.5925781225508751590"));
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see at.jku.ce.airline.service.AirlineServiceImpl#getAirline(*
	 */
	@Override
	public at.jku.ce.airline.service.Airline getAirline() {
		LOG.info("Executing operation getAirline");
		try {
			at.jku.ce.airline.service.Airline _return = new at.jku.ce.airline.service.Airline();
			java.util.List<at.jku.ce.airline.service.Flight> _returnFlightPlan = new java.util.ArrayList<at.jku.ce.airline.service.Flight>();
			at.jku.ce.airline.service.Flight _returnFlightPlanVal1 = new at.jku.ce.airline.service.Flight();
			at.jku.ce.airline.service.Time _returnFlightPlanVal1ArrivalTime = new at.jku.ce.airline.service.Time();
			_returnFlightPlanVal1ArrivalTime.setIndexDayOfWeek(1209099659);
			_returnFlightPlanVal1ArrivalTime
					.setTimeOfDay(-5353814419110968034l);
			_returnFlightPlanVal1
					.setArrivalTime(_returnFlightPlanVal1ArrivalTime);
			at.jku.ce.airline.service.Airport _returnFlightPlanVal1ArrivesAt = new at.jku.ce.airline.service.Airport();
			_returnFlightPlanVal1ArrivesAt
					.setAirportTax(new java.math.BigDecimal(
							"-8253921849180408379.2441569302130572329"));
			_returnFlightPlanVal1ArrivesAt.setCity("City-1359302221");
			_returnFlightPlanVal1ArrivesAt.setCountry("Country-972230831");
			_returnFlightPlanVal1ArrivesAt.setIcao("Icao-434529804");
			_returnFlightPlanVal1ArrivesAt.setName("Name-1410873041");
			_returnFlightPlanVal1.setArrivesAt(_returnFlightPlanVal1ArrivesAt);
			at.jku.ce.airline.service.Airport _returnFlightPlanVal1DepartesFrom = new at.jku.ce.airline.service.Airport();
			_returnFlightPlanVal1DepartesFrom
					.setAirportTax(new java.math.BigDecimal(
							"-4667064469381352116.688078325247495839"));
			_returnFlightPlanVal1DepartesFrom.setCity("City-1609691253");
			_returnFlightPlanVal1DepartesFrom.setCountry("Country-1591576357");
			_returnFlightPlanVal1DepartesFrom.setIcao("Icao193827007");
			_returnFlightPlanVal1DepartesFrom.setName("Name1392201405");
			_returnFlightPlanVal1
					.setDepartesFrom(_returnFlightPlanVal1DepartesFrom);
			at.jku.ce.airline.service.Time _returnFlightPlanVal1DepartureTime = new at.jku.ce.airline.service.Time();
			_returnFlightPlanVal1DepartureTime.setIndexDayOfWeek(-562433307);
			_returnFlightPlanVal1DepartureTime
					.setTimeOfDay(4761023990042851763l);
			_returnFlightPlanVal1
					.setDepartureTime(_returnFlightPlanVal1DepartureTime);
			_returnFlightPlanVal1.setFlightId("FlightId976194485");
			_returnFlightPlanVal1.setPlaneName("PlaneName1339099343");
			_returnFlightPlanVal1.setStdFee(new java.math.BigDecimal(
					"-7897875278579311711.1506431041129654009"));
			_returnFlightPlan.add(_returnFlightPlanVal1);
			_return.getFlightPlan().addAll(_returnFlightPlan);
			_return.setName("Name937139532");
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * at.jku.ce.airline.service.AirlineServiceImpl#bookFlight(java.lang.String
	 * bookingUuid ,)java.lang.String flightId
	 * ,)javax.xml.datatype.XMLGregorianCalendar flightDate )*
	 */
	@Override
	public boolean bookFlight(java.lang.String bookingUuid,
			java.lang.String flightId,
			javax.xml.datatype.XMLGregorianCalendar flightDate) {
		LOG.info("Executing operation bookFlight");
		System.out.println(bookingUuid);
		System.out.println(flightId);
		System.out.println(flightDate);
		try {
			boolean _return = false;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * at.jku.ce.airline.service.AirlineServiceImpl#cancelFlight(java.lang.String
	 * bookingUuid ,)java.lang.String flightId )*
	 */
	@Override
	public boolean cancelFlight(java.lang.String bookingUuid,
			java.lang.String flightId) {
		LOG.info("Executing operation cancelFlight");
		System.out.println(bookingUuid);
		System.out.println(flightId);
		try {
			boolean _return = true;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
